name: Deploy to Private EC2 via Bastion

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Bastion Key
      run: |
        echo "${{ secrets.BASTION_KEY }}" > bastion_key.pem
        chmod 600 bastion_key.pem

    - name: Upload code to Bastion
      run: |
        scp -i bastion_key.pem -o StrictHostKeyChecking=no -r . \
        ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:/tmp/app

    - name: SSH into Bastion and forward to Private EC2
      run: |
        ssh -i bastion_key.pem -o StrictHostKeyChecking=no \
        ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} << 'EOF'
          # Inside Bastion: Forward to Private EC2
          scp -i /home/ec2-user/pd-key-name.pem -o StrictHostKeyChecking=no -r /tmp/app \
          ${{ secrets.PRIVATE_USER }}@${{ secrets.PRIVATE_IP }}:/home/${{ secrets.PRIVATE_USER }}/apps
        EOF
