name: Deploy to Private EC2 via Bastion

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Bastion Key
      run: |
        echo "${{ secrets.BASTION_KEY }}" > bastion_key.pem
        chmod 600 bastion_key.pem

    - name: Archive code excluding unwanted files
      run: |
        tar --exclude='.git' --exclude='.github' --exclude='.DS_Store' -czf app.tar.gz . || true

    - name: Copy archive to Bastion
      run: |
        scp -i bastion_key.pem -o StrictHostKeyChecking=no app.tar.gz \
        ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }}:/tmp/

    - name: SSH into Bastion and forward archive to Private EC2
      run: |
        ssh -i bastion_key.pem -o StrictHostKeyChecking=no \
        ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} << 'EOF'
          # Forward the archive to the private EC2
          scp -i /home/ec2-user/private_key.pem -o StrictHostKeyChecking=no /tmp/app.tar.gz \
          ${{ secrets.PRIVATE_USER }}@${{ secrets.PRIVATE_IP }}:/tmp/

          # Extract the archive into /apps directory
          ssh -i /home/ec2-user/private_key.pem -o StrictHostKeyChecking=no \
          ${{ secrets.PRIVATE_USER }}@${{ secrets.PRIVATE_IP }} \
          "sudo mkdir -p /apps && sudo tar -xzf /tmp/app.tar.gz -C /apps && sudo chown -R $USER:$USER /apps"
        EOF
